### PR TITLE
GH-37: Update Cake.Figlet to target Cake v1.0.0

### LINKED ISSUE #37: Update Cake.Figlet to target Cake v1.0.0
https://cakebuild.net/blog/2021/02/cake-v1.0.0-released

### PR DESCRIPTION
**Pull request by augustoproiete**
Closes #37

### CODE REVIEW

**Comment by pascalberger** [comment]
I would suggest to not update this addin to 1.0, but instead deprecate it since FIGlet support comes now out of the box with Cake 1.x: https://github.com/cake-contrib/Cake.Figlet/issues/38

**Comment by augustoproiete** [comment]
I saw #38 but what I understood is that there's work we need to do before it becomes 1st class - e.g. Aliases, which would come in a Cake v1.x version - is that not the case?

We'd also need to update Cake.Recipe to use the new way...

I also don't think we have any docs on how to use the new Figlet support yet - or do we?

All-in-all I'm thinking the cost of releasing a new version of this addin targeting Cake v1.0 is so small that we could release and immediately deprecate it. Cake.Figlet v1.0 will continue to work until Cake v2.0 comes out... Everyone wins... Unblocks Cake.Recipe and anyone wanting to use this addin with Cake v1.0 without getting warnings.

**Comment by pascalberger** [comment]
You already can use it with 1.0:

```
AnsiConsole.Render(
    new FigletText("Hello")
        .LeftAligned()
        .Color(Color.Red));
```

I can add some documentation mentioning Spectre.Console support on Cake website.

While I agree that it is not much work to ship an 1.0 version of this addin, what makes me hesitant is that we probably will ship same alias names with a 1.x release and then it will break. So it might be an easier upgrade path for users if this addin is not officially supported for 1.x, deprecated and pointing to relevant documentation on Cake website instead..

**Comment by pascalberger** [comment]
Another option would be to release a 1.0 version of Cake.Figlet, add documentation to Cake website how to use Spectre.Console directly, but wait with providing Figlet Alias in Cake for 2.0 and then deprecate this addin after 1.0

**Comment by augustoproiete** [comment]
I think the second option is a better experience for devs using Cake.Figlet today, who want to upgrade to Cake v1.0, as all they have to do is update the `&version` segment of the #addin and they're good to go, without having to change actual build code.

**Comment by nils-a** [comment]
Would it be possible to update to Cake 1.0 here and add a deprecation attribute to the aliases? 
So people can see the warning. Then, when we ship a same-named alias things will be broken but everyone was warned..

**Comment by augustoproiete** [comment]
@nils-a It would be possible, although in practice that would mean we are trading one warning with another one.

Cake.Figlet works fine with Cake 1.0, except that Cake displays a warning, which as a user of this addin I would prefer not to have it displayed in my build logs:

```
The assembly 'Cake.Figlet, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
For best compatibility it should target Cake.Core version 1.0.0.
```

Updating Cake.Figlet to target Cake v1.0 and releasing Cake v1.0 (by merging this PR as-is) makes sense to me right now, because it makes the experience of upgrading from Cake 0.x to 1.0 better for existing users of this addin (i.e. no more warnings).

My suggestion would be:

1. Release Cake.Figlet v1.0.0 (targeting Cake v1.0.0) now
2. Once Cake v1.x ships including Figlet aliases, we deprecate this addin (in nuget.org) and document the upgrade path
3. (Optionally) we could add a feature in Cake that detects usage of deprecated addins and displays a warning (and possibly refuse to load it). I think a similar feature for blacklisting assemblies already exists in Cake, so maybe it could be as simple as including `Cake.Figlet.dll` in the list

**Comment by nils-a** [comment]
Agreed. 
Maybe we could add a hint here in readme or release notes that Cake.Figlet will be deprecated soon?

**Comment by gep13** [comment]
This was rebased and merged into develop here: https://github.com/cake-contrib/Cake.Figlet/commit/c2cffc9fb5fd188ed3ee9628178b1cf2e6af403a

**Comment by gep13** [comment]
@augustoproiete thank you very much for getting this updated!

**Pull request closed without merging**
