### PR TITLE
(GH-10) Target .NET Standard 2.0 and build against Cake 0.26.0

### LINKED ISSUE #10: Build against Cake 0.26.0
Cake 0.26.0 introduced breaking changes. To support Cake versions >= 0.26.0 this addin should be built against Cake 0.26.0

### PR DESCRIPTION
**Pull request by pascalberger**
Target .NET Standard 2.0 and build against Cake 0.26.0

Fixes #10

### CODE REVIEW

**Comment by pascalberger** [comment]
Build should be fixed once #13 is merged and this is rebased on master.

**Comment by phil-scott-78** [comment]
Interesting - this seems to be happening running the tests. I suspect this [issue might be at play](https://github.com/xunit/xunit/issues/1573)

**Comment by phil-scott-78** [comment]
yup, just pulled it down locally and tested it out. Fails then adding 

    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>

gets things back in order

**Comment by pascalberger** [comment]
@enkafan Added `RuntimeFrameworkVersion`

**Comment by phil-scott-78** [comment]
build issue is related to the current build script not being very good. everything else LGTM so I'll get this merged and a new version pushed.

**Comment by phil-scott-78** [comment]
ok, things look to be all good. Nuget has indexed [v1.1](https://www.nuget.org/packages/Cake.Figlet/1.1.0) which contains these updates.

Thanks!

**Pull request merged**
